# Generated by Django 4.0 on 2022-07-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
    ]
