# Generated by Django 4.0 on 2022-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='star',
            field=models.TextField(default='0', max_length=1),
        ),
    ]
