# Generated by Django 4.0 on 2022-07-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='profilePhotos'),
        ),
    ]
