# Generated by Django 4.0 on 2022-07-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(default='default.jpg', upload_to='profilePhotos'),
        ),
    ]
